_wandb:
    value:
        cli_version: 0.19.0
        m: []
        python_version: 3.10.5
        t:
            "1":
                - 1
                - 41
                - 55
            "2":
                - 1
                - 41
                - 55
            "3":
                - 23
                - 55
            "4": 3.10.5
            "5": 0.19.0
            "8":
                - 5
            "12": 0.19.0
            "13": darwin-arm64
