_wandb:
    value:
        cli_version: 0.18.7
        m: []
        python_version: 3.9.21
        t:
            "1":
                - 1
                - 41
                - 55
            "2":
                - 1
                - 41
                - 55
            "3":
                - 13
                - 16
                - 23
                - 55
            "4": 3.9.21
            "5": 0.18.7
            "8":
                - 5
            "12": 0.18.7
            "13": linux-x86_64
batch_size:
    value: 16
beta1:
    value: 0.5
beta2:
    value: 0.999
learning_rate:
    value: 0.0002
num_epochs:
    value: 200
